version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: world
    ports:
      - "3307:3306" #호스트:컨테이너

  inovation:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/world
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    network_mode: host
    depends_on:
      - mysql
      - redis
