spring:
  redis:
    data:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/world
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      org.springframework.security: INFO
naver:
  api:
    clientId: 5_6vnGOcaeUbwJbdyF1q
    clientSecret: s034WsHYTi

jwt:
  secretKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

#설정을 통해 더 다양한 정보들을 제공 받을 수 있습니다.

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    shutdown:
#      enabled: true

#health, info만 노출
#management:
#  endpoints:
#    jmx:
#      exposure:
#        include: "health,info"

# env, beans를 제회라고 전부 노출
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "env,beans"

# health의 상세정보
#management:
#  endpoint:
#    health:
#      show-details: always

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true