spring:
  redis:
    data:
      host: redis
      port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/world
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      org.springframework.security: INFO
naver:
  api:
    clientId: 5_6vnGOcaeUbwJbdyF1q
    clientSecret: s034WsHYTi

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK


management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    os:
      enabled: true